export const AnalyticsData = {
  symbols: [
    ["BINANCE:BTCUSDT|1M"],
    ["BINANCE:ETHUSDT|1M"],
    ["BINANCE:DOGEUSDT|1M"],
    ["BINANCE:SOLUSDT|1M"],
    ["BINANCE:DASHUSDT|1M"],
    ["BINANCE:LTCUSDT|1M"],
  ],
  chartOnly: false,
  width: 550,
  height: 400,
  locale: "en",
  colorTheme: "dark",
  autosize: true,
  showVolume: false,
  showMA: false,
  hideDateRanges: false,
  hideMarketStatus: false,
  hideSymbolLogo: false,
  scalePosition: "right",
  scaleMode: "Normal",
  fontFamily:
    "-apple-system, BlinkMacSystemFont, Trebuchet MS, Roboto, Ubuntu, sans-serif",
  fontSize: "10",
  noTimeScale: false,
  valuesTracking: "1",
  changeMode: "price-and-percent",
  chartType: "area",
  maLineColor: "#2962FF",
  maLineWidth: 1,
  maLength: 9,
  lineWidth: 1,
  lineType: 0,
  dateRanges: ["1d|1", "1m|30", "3m|60", "12m|1D", "60m|1W", "all|1M"],
  upColor: "#22ab94",
  downColor: "#f7525f",
  borderUpColor: "#22ab94",
  borderDownColor: "#f7525f",
  wickUpColor: "#22ab94",
  wickDownColor: "#f7525f",
};
